# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import shopsubjectcopyservice_pb2 as shopsubjectcopyservice__pb2


class ShopSubjectCopyServiceStub(object):
    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.shopSubjectCopy = channel.unary_unary(
            '/ShopSubjectCopyService/shopSubjectCopy',
            request_serializer=shopsubjectcopyservice__pb2.ShopSubjectCopyRequest.SerializeToString,
            response_deserializer=shopsubjectcopyservice__pb2.ShopSubjectCopyResponse.FromString,
        )


class ShopSubjectCopyServiceServicer(object):
    def shopSubjectCopy(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopSubjectCopyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'shopSubjectCopy': grpc.unary_unary_rpc_method_handler(
            servicer.shopSubjectCopy,
            request_deserializer=shopsubjectcopyservice__pb2.ShopSubjectCopyRequest.FromString,
            response_serializer=shopsubjectcopyservice__pb2.ShopSubjectCopyResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ShopSubjectCopyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
