# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopsubjectcopyservice.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import commons_pb2 as commons__pb2
import beancommons_pb2 as beancommons__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='shopsubjectcopyservice.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x1cshopsubjectcopyservice.proto\x1a\rcommons.proto\x1a\x11\x62\x65\x61ncommons.proto\"\x92\x01\n\x16ShopSubjectCopyRequest\x12\x14\n\x0csourceShopID\x18\x02 \x01(\x03\x12\x14\n\x0ctargetShopID\x18\x03 \x01(\x03\x12\x15\n\rsourceGroupID\x18\x04 \x01(\x03\x12\x15\n\rtargetGroupID\x18\x05 \x01(\x03\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.RequestHeader\"8\n\x17ShopSubjectCopyResponse\x12\x1d\n\x06result\x18\x01 \x01(\x0b\x32\r.ResultHeader2`\n\x16ShopSubjectCopyService\x12\x46\n\x0fshopSubjectCopy\x12\x17.ShopSubjectCopyRequest\x1a\x18.ShopSubjectCopyResponse\"\x00\x42\x30\n\x19\x63om.hualala.app.shop.grpcB\x13ShopSubjectCopyDatab\x06proto3')
    ,
    dependencies=[commons__pb2.DESCRIPTOR, beancommons__pb2.DESCRIPTOR, ])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SHOPSUBJECTCOPYREQUEST = _descriptor.Descriptor(
    name='ShopSubjectCopyRequest',
    full_name='ShopSubjectCopyRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='sourceShopID', full_name='ShopSubjectCopyRequest.sourceShopID', index=0,
            number=2, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='targetShopID', full_name='ShopSubjectCopyRequest.targetShopID', index=1,
            number=3, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='sourceGroupID', full_name='ShopSubjectCopyRequest.sourceGroupID', index=2,
            number=4, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='targetGroupID', full_name='ShopSubjectCopyRequest.targetGroupID', index=3,
            number=5, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='header', full_name='ShopSubjectCopyRequest.header', index=4,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=67,
    serialized_end=213,
)

_SHOPSUBJECTCOPYRESPONSE = _descriptor.Descriptor(
    name='ShopSubjectCopyResponse',
    full_name='ShopSubjectCopyResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='result', full_name='ShopSubjectCopyResponse.result', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=215,
    serialized_end=271,
)

_SHOPSUBJECTCOPYREQUEST.fields_by_name['header'].message_type = commons__pb2._REQUESTHEADER
_SHOPSUBJECTCOPYRESPONSE.fields_by_name['result'].message_type = commons__pb2._RESULTHEADER
DESCRIPTOR.message_types_by_name['ShopSubjectCopyRequest'] = _SHOPSUBJECTCOPYREQUEST
DESCRIPTOR.message_types_by_name['ShopSubjectCopyResponse'] = _SHOPSUBJECTCOPYRESPONSE

ShopSubjectCopyRequest = _reflection.GeneratedProtocolMessageType('ShopSubjectCopyRequest', (_message.Message,), dict(
    DESCRIPTOR=_SHOPSUBJECTCOPYREQUEST,
    __module__='shopsubjectcopyservice_pb2'
    # @@protoc_insertion_point(class_scope:ShopSubjectCopyRequest)
))
_sym_db.RegisterMessage(ShopSubjectCopyRequest)

ShopSubjectCopyResponse = _reflection.GeneratedProtocolMessageType('ShopSubjectCopyResponse', (_message.Message,), dict(
    DESCRIPTOR=_SHOPSUBJECTCOPYRESPONSE,
    __module__='shopsubjectcopyservice_pb2'
    # @@protoc_insertion_point(class_scope:ShopSubjectCopyResponse)
))
_sym_db.RegisterMessage(ShopSubjectCopyResponse)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                _b('\n\031com.hualala.app.shop.grpcB\023ShopSubjectCopyData'))
try:
    # THESE ELEMENTS WILL BE DEPRECATED.
    # Please use the generated *_pb2_grpc.py files instead.
    import grpc
    from grpc.beta import implementations as beta_implementations
    from grpc.beta import interfaces as beta_interfaces
    from grpc.framework.common import cardinality
    from grpc.framework.interfaces.face import utilities as face_utilities


    class ShopSubjectCopyServiceStub(object):

        def __init__(self, channel):
            """Constructor.

            Args:
              channel: A grpc.Channel.
            """
            self.shopSubjectCopy = channel.unary_unary(
                '/ShopSubjectCopyService/shopSubjectCopy',
                request_serializer=ShopSubjectCopyRequest.SerializeToString,
                response_deserializer=ShopSubjectCopyResponse.FromString,
            )


    class ShopSubjectCopyServiceServicer(object):

        def shopSubjectCopy(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details('Method not implemented!')
            raise NotImplementedError('Method not implemented!')


    def add_ShopSubjectCopyServiceServicer_to_server(servicer, server):
        rpc_method_handlers = {
            'shopSubjectCopy': grpc.unary_unary_rpc_method_handler(
                servicer.shopSubjectCopy,
                request_deserializer=ShopSubjectCopyRequest.FromString,
                response_serializer=ShopSubjectCopyResponse.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            'ShopSubjectCopyService', rpc_method_handlers)
        server.add_generic_rpc_handlers((generic_handler,))


    class BetaShopSubjectCopyServiceServicer(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def shopSubjectCopy(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


    class BetaShopSubjectCopyServiceStub(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def shopSubjectCopy(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()

        shopSubjectCopy.future = None


    def beta_create_ShopSubjectCopyService_server(servicer, pool=None, pool_size=None, default_timeout=None,
                                                  maximum_timeout=None):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_deserializers = {
            ('ShopSubjectCopyService', 'shopSubjectCopy'): ShopSubjectCopyRequest.FromString,
        }
        response_serializers = {
            ('ShopSubjectCopyService', 'shopSubjectCopy'): ShopSubjectCopyResponse.SerializeToString,
        }
        method_implementations = {
            ('ShopSubjectCopyService', 'shopSubjectCopy'): face_utilities.unary_unary_inline(servicer.shopSubjectCopy),
        }
        server_options = beta_implementations.server_options(request_deserializers=request_deserializers,
                                                             response_serializers=response_serializers,
                                                             thread_pool=pool, thread_pool_size=pool_size,
                                                             default_timeout=default_timeout,
                                                             maximum_timeout=maximum_timeout)
        return beta_implementations.server(method_implementations, options=server_options)


    def beta_create_ShopSubjectCopyService_stub(channel, host=None, metadata_transformer=None, pool=None,
                                                pool_size=None):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_serializers = {
            ('ShopSubjectCopyService', 'shopSubjectCopy'): ShopSubjectCopyRequest.SerializeToString,
        }
        response_deserializers = {
            ('ShopSubjectCopyService', 'shopSubjectCopy'): ShopSubjectCopyResponse.FromString,
        }
        cardinalities = {
            'shopSubjectCopy': cardinality.Cardinality.UNARY_UNARY,
        }
        stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer,
                                                         request_serializers=request_serializers,
                                                         response_deserializers=response_deserializers,
                                                         thread_pool=pool, thread_pool_size=pool_size)
        return beta_implementations.dynamic_stub(channel, 'ShopSubjectCopyService', cardinalities, options=stub_options)
except ImportError:
    pass
# @@protoc_insertion_point(module_scope)
